on:
  push:
  pull_request:
    branches: [trunk]
jobs:
  build:
    name: Run specs
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get -qy install libuchardet-dev
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Run tests
        run: crystal spec --order=random --error-on-warnings
